version: '3'

services:
  app:
    build: .
    # uncomment for dev:
    # volumes:
    #   - ./:/app
    ports:
      - 8000:8000
    depends_on:
      - mysql
    # uncomment for dev:
    # command: nodemon server_script.js

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql-data:
